# Generated by Django 5.0.6 on 2024-05-25 07:25

import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=500, null=True)),
                ('License', models.CharField(max_length=15)),
            ],
        ),
    ]
