# Generated by Django 5.0.6 on 2024-05-25 07:43

import django.db.models.deletion
import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='vehi',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.vehicle'),
        ),
    ]
