# Generated by Django 5.0.6 on 2024-05-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_tour_vehi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='vehi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vehicle'),
        ),
    ]
