# Generated by Django 5.0.6 on 2024-05-25 07:49

import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_tour_vehi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='vehi',
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle',
            field=models.CharField( max_length=100),
        ),
    ]
