# Generated by Django 5.0.6 on 2024-06-01 19:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_like_tour_active_alter_album_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 2, 1, 34, 510073)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 2, 1, 34, 510073)),
        ),
        migrations.AlterField(
            model_name='tour_image',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.album'),
        ),
    ]
