# Generated by Django 5.0.6 on 2024-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_tour_vehi_tour_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='vehicle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
