# Generated by Django 5.0.6 on 2024-06-01 19:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_album_created_date_alter_image_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 2, 37, 6, 296033)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 2, 37, 6, 297420)),
        ),
        migrations.DeleteModel(
            name='Tour_Image',
        ),
    ]
