# Generated by Django 5.0.6 on 2024-06-03 04:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_tour_album_alter_album_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Pic',
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 28, 33, 253857)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 28, 33, 253857)),
        ),
        migrations.CreateModel(
            name='Tour_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.album')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.image')),
            ],
        ),
    ]
