# Generated by Django 5.0.6 on 2024-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_tour_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='vehicle',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
