# Generated by Django 5.0.6 on 2024-05-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_tour_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='vehicle',
        ),
    ]
