# Generated by Django 5.0.6 on 2024-06-03 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_image_pic_alter_album_created_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_Image',
            new_name='Album_Image',
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 31, 47, 939704)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 31, 47, 940739)),
        ),
    ]
