# Generated by Django 5.0.6 on 2024-06-03 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_rename_tour_image_album_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_id',
            field=models.ManyToManyField(to='travel.image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 45, 35, 436453)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 45, 35, 436453)),
        ),
        migrations.DeleteModel(
            name='Album_Image',
        ),
    ]
