# Generated by Django 5.0.6 on 2024-06-03 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_album_image_id_alter_album_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 47, 28, 607665)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 47, 28, 606665)),
        ),
    ]
