# Generated by Django 5.0.6 on 2024-05-25 08:03

import django.db.models.deletion
import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_tour_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('License', models.CharField(max_length=15)),

            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='tour',
            name='Vehicle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.transport'),
        ),
    ]
