# Generated by Django 5.0.6 on 2024-06-11 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_album_created_date_alter_image_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 10, 23, 32, 687530)),
        ),
        migrations.AlterField(
            model_name='image',
            name='Path',
            field=models.ImageField(upload_to='imageForTour/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 10, 23, 32, 686384)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_thumbnail',
            field=models.ImageField(upload_to='news/%Y/%m'),
        ),
    ]
