# Generated by Django 5.0.6 on 2024-05-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_tour_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
