# Generated by Django 4.2.13 on 2024-06-11 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0015_alter_album_created_date_alter_image_path_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmt_news",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="cmt_news",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.RenameField(
            model_name="cmt_tour",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="cmt_tour",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.RenameField(
            model_name="rating_tour",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="rating_tour",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="Ngày đăng",
            new_name="DatePost",
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="Ngày cập nhật",
            new_name="DateUpdate",
        ),
        migrations.AlterField(
            model_name="album",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 11, 15, 42, 19, 973438)
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 11, 15, 42, 19, 972455)
            ),
        ),
    ]
