# Generated by Django 5.0.6 on 2024-06-15 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_schedule_departuretime_alter_album_created_date_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 10, 10, 58, 451309)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 10, 10, 58, 450309)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='DepartureDay',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vaitro',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=30),
        ),
    ]
