# Generated by Django 5.0.6 on 2024-05-25 08:27

import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_tour_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vehicle',
            field=models.CharField( max_length=100),
        ),
    ]
