# Generated by Django 5.0.6 on 2024-05-25 08:28

import travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_transport_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Vehicle',
            field=models.CharField( max_length=100),
        ),
    ]
