# Generated by Django 5.0.6 on 2024-06-15 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_album_created_date_alter_image_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(default=1, max_length=1000, upload_to='Travel/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 15, 35, 28, 532535)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 15, 35, 28, 531164)),
        ),
    ]
