# Generated by Django 5.0.6 on 2024-06-16 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_remove_customer_avatar_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktour',
            name='id_customer_bt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 3, 9, 0, 221382)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 3, 9, 0, 221382)),
        ),
    ]
