# Generated by Django 5.0.6 on 2024-06-17 15:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_booktour_id_customer_bt_alter_album_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktour',
            name='Ngày cập nhật',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booktour',
            name='Ngày đăng',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 22, 21, 51, 285764)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 22, 21, 51, 284774)),
        ),
    ]
