# Generated by Django 5.0.6 on 2024-05-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_remove_transport_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='Vehicle',
            new_name='vehicle',
        ),
    ]
