# Generated by Django 5.0.6 on 2024-06-17 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_booktour_ngày_cập_nhật_booktour_ngày_đăng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktour',
            name='Ngày cập nhật',
        ),
        migrations.RemoveField(
            model_name='booktour',
            name='Ngày đăng',
        ),
        migrations.AddField(
            model_name='booktour',
            name='Days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktour',
            name='DeparturePlace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Place.Tour_set+', to='travel.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktour',
            name='DepartureTime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktour',
            name='Destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktour',
            name='Nights',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktour',
            name='vehicle',
            field=models.ForeignKey(default='____', null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.transport'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 22, 33, 53, 546183)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 22, 33, 53, 544676)),
        ),
    ]
