# Generated by Django 5.0.6 on 2024-06-20 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_remove_booktour_ngày_cập_nhật_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 15, 2, 48, 618743)),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 15, 2, 48, 617742)),
        ),
    ]
