# Generated by Django 5.0.6 on 2024-05-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_alter_tour_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.image'),
        ),
    ]
