# Generated by Django 5.0.6 on 2024-05-25 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_tour_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Path',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
