# Generated by Django 5.0.6 on 2024-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_alter_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
