# Generated by Django 5.0.6 on 2024-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.album'),
            preserve_default=False,
        ),
    ]
