# Generated by Django 5.0.6 on 2024-05-26 03:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_image_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='picture',
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 10, 18, 57, 933890)),
        ),
        migrations.CreateModel(
            name='Tour_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngày đăng', models.DateTimeField(auto_now_add=True)),
                ('Ngày cập nhật', models.DateTimeField(auto_now=True)),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.image')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travel.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
