# Generated by Django 5.0.6 on 2024-05-26 03:45

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_remove_tour_picture_alter_image_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 10, 45, 23, 924352)),
        ),
    ]
