# Generated by Django 5.0.6 on 2024-05-26 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0036_news_content_alter_cmt_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 11, 15, 26, 388015)),
        ),
        migrations.AlterUniqueTogether(
            name='cmt_news',
            unique_together={('news', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='cmt_tour',
            unique_together={('tour', 'user')},
        ),
    ]
